sudo: false
language: node_js
node_js:
- '6'
env:
- TSI2_LING7='build'
- TSI2_LING7='test'
branches:
  only:
  - master
script:
- echo npm run $TSI2_LING7
- npm run $TSI2_LING7
deploy:
  provider: pages
  fqdn: asr-backend.iis.sinica.edu.tw
  skip_cleanup: true
  local_dir: build/
  github_token: $GITHUB_TOKEN
  on:
    branch: master
